// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCarsrxVi7FAdzmxVwwCbpI8wWHRCjcxys',
    appId: '1:406131643426:web:eda38515bcedc073f6a67b',
    messagingSenderId: '406131643426',
    projectId: 'diaries-club-app',
    authDomain: 'diaries-club-app.firebaseapp.com',
    storageBucket: 'diaries-club-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSMHwpJAX8mzuH-qo-BsWJgB1Pmpsx0qg',
    appId: '1:406131643426:ios:e12707a4338b1624f6a67b',
    messagingSenderId: '406131643426',
    projectId: 'diaries-club-app',
    storageBucket: 'diaries-club-app.firebasestorage.app',
    iosBundleId: 'com.diariesclub.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwlWDGgPr0xtkTl0_J4LWkvCkH-YGn5ao',
    appId: '1:406131643426:android:9d174d37105ee772f6a67b',
    messagingSenderId: '406131643426',
    projectId: 'diaries-club-app',
    storageBucket: 'diaries-club-app.firebasestorage.app',
  );

}