-- ===========================================================================
--  Migration 0040 — Birthday packages rich-data schema (Module 2.7)
--
--  Adds the four JSONB knobs the rich admin form needs + a cached PDF
--  URL slot. Existing columns covered already:
--    name, tier, description, cover_image_url, gallery_image_urls (TEXT[]),
--    price_paise, duration_hours, max_kids, max_adults, inclusions (JSONB),
--    hero_theme, deposit_paise, is_active, sort_order
--
--  New JSONB columns:
--    menu_options        — customer-selectable menu choices (cake variants,
--                           drink choices, dessert variants).
--                           Shape: [{"category":"Cake","options":[{"id":"...",
--                                    "name":"Chocolate","upcharge_paise":0}]},...]
--    non_food_offerings  — decoration / music / photographer / return-gifts
--                           breakdown for the PDF.
--                           Shape: [{"label":"Decoration","detail":"Theme-based"}, ...]
--    available_days      — {"weekend":true, "weekday":true, "specific_dates":[...]}
--    pdf_url             — cached PDF generated by the Edge function.
--                           Regenerated whenever admin saves an edit.
--
--  Storage bucket package-pdfs (public per ARCHITECTURE-001 — promotional
--  document, no PII).
-- ===========================================================================

BEGIN;

ALTER TABLE birthday_packages
  ADD COLUMN IF NOT EXISTS menu_options JSONB DEFAULT '[]'::JSONB,
  ADD COLUMN IF NOT EXISTS non_food_offerings JSONB DEFAULT '[]'::JSONB,
  ADD COLUMN IF NOT EXISTS available_days JSONB DEFAULT
    '{"weekend":true,"weekday":true,"specific_dates":[]}'::JSONB,
  ADD COLUMN IF NOT EXISTS pdf_url TEXT;

-- Storage: package-pdfs bucket (public, like menu-photos / package-photos).
INSERT INTO storage.buckets (id, name, public)
VALUES ('package-pdfs', 'package-pdfs', TRUE)
ON CONFLICT (id) DO UPDATE SET public = TRUE;

DROP POLICY IF EXISTS "package_pdfs_authenticated_read" ON storage.objects;
CREATE POLICY "package_pdfs_authenticated_read"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'package-pdfs');

DROP POLICY IF EXISTS "package_pdfs_service_role_write" ON storage.objects;
CREATE POLICY "package_pdfs_service_role_write"
  ON storage.objects FOR ALL
  TO service_role
  USING (bucket_id = 'package-pdfs')
  WITH CHECK (bucket_id = 'package-pdfs');

COMMIT;
