-- ===========================================================================
--  Migration 0049 — admin web storage write policies
--
--  Bug surfaced during workshops UI re-test (BUG-050): admin tried to
--  upload a workshop cover photo and hit
--    StorageException: new row violates row-level security policy (403)
--
--  Root cause: every admin-managed bucket (workshop-photos, menu-photos,
--  package-photos, hero-cards) had read policies for `authenticated` and
--  WRITE policies for `service_role` only. The admin web logs in as a
--  regular authenticated user (Supabase Auth email/password), so its JWT
--  has role='authenticated' and the existing service-role-only write
--  policies block all uploads from the admin UI.
--
--  Two fix paths:
--    1. Route every photo upload through an Edge Function holding the
--       service-role key. Heavier — adds a hop to every upload, makes
--       progress UI harder, and we don't gain anything because the
--       admin user IS already authorised in admin_users.
--    2. Add admin-scoped storage policies that allow writes when the
--       authenticated user is in admin_users AND is_active=true. Same
--       pattern as the existing admin_users gate on every admin RPC.
--       This is what the policies below do.
--
--  Buckets covered:
--    workshop-photos  — workshops cover_image_url
--    menu-photos      — coffee menu_items.photo_url
--    package-photos   — birthday_packages.cover_image_url + gallery
--    hero-cards       — hero_card_definitions.image_url (placeholder swap)
--
--  Buckets intentionally NOT covered (writes stay service-role-only):
--    hero-recaps      — generated by generate-hero-recap-image Edge Fn
--    package-pdfs     — generated by birthday-package-pdf Edge Fn
--    invoices         — generated server-side
--    birthday-photos  — customer uploads, owner-scoped
--    child-photos     — customer uploads, owner-scoped
--
--  Reversibility:
--    DROP POLICY workshop_photos_admin_write ON storage.objects;
--    -- and 3 more, one per bucket
-- ===========================================================================

-- One policy per bucket. FOR ALL covers INSERT/UPDATE/DELETE in one
-- statement; the redundancy with the existing *_authenticated_read
-- SELECT policies is harmless (PostgreSQL OR's permissive policies).
-- Predicate: caller's auth.uid() must be in admin_users + is_active.

CREATE POLICY workshop_photos_admin_write ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'workshop-photos'
    AND EXISTS (
      SELECT 1 FROM public.admin_users
       WHERE auth_user_id = auth.uid() AND is_active = true
    )
  )
  WITH CHECK (
    bucket_id = 'workshop-photos'
    AND EXISTS (
      SELECT 1 FROM public.admin_users
       WHERE auth_user_id = auth.uid() AND is_active = true
    )
  );

CREATE POLICY menu_photos_admin_write ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'menu-photos'
    AND EXISTS (
      SELECT 1 FROM public.admin_users
       WHERE auth_user_id = auth.uid() AND is_active = true
    )
  )
  WITH CHECK (
    bucket_id = 'menu-photos'
    AND EXISTS (
      SELECT 1 FROM public.admin_users
       WHERE auth_user_id = auth.uid() AND is_active = true
    )
  );

CREATE POLICY package_photos_admin_write ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'package-photos'
    AND EXISTS (
      SELECT 1 FROM public.admin_users
       WHERE auth_user_id = auth.uid() AND is_active = true
    )
  )
  WITH CHECK (
    bucket_id = 'package-photos'
    AND EXISTS (
      SELECT 1 FROM public.admin_users
       WHERE auth_user_id = auth.uid() AND is_active = true
    )
  );

CREATE POLICY hero_cards_admin_write ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'hero-cards'
    AND EXISTS (
      SELECT 1 FROM public.admin_users
       WHERE auth_user_id = auth.uid() AND is_active = true
    )
  )
  WITH CHECK (
    bucket_id = 'hero-cards'
    AND EXISTS (
      SELECT 1 FROM public.admin_users
       WHERE auth_user_id = auth.uid() AND is_active = true
    )
  );
