BEGIN;

DROP FUNCTION IF EXISTS admin_menu_item_create(UUID, TEXT, TEXT, INTEGER, TEXT, TEXT, INTEGER);
DROP FUNCTION IF EXISTS admin_menu_item_update(UUID, TEXT, TEXT, INTEGER, TEXT, TEXT, BOOLEAN, BOOLEAN);

COMMIT;
